const DELETE=1;
const EDIT_BUTTON=2;
const RESET_FORM=3;
const SET_LOADING=4;
const FETCH_COMPLETE=5;
const HANDLE_CHANGES=6;
const SUBMIT_COMPLETE=7;
const HANDLE_IMAGE=8;
const HANDLE_EDIT_PROFILE=9;
export {
    DELETE,EDIT_BUTTON,RESET_FORM, SET_LOADING, FETCH_COMPLETE, HANDLE_CHANGES, SUBMIT_COMPLETE, HANDLE_IMAGE, HANDLE_EDIT_PROFILE
}
