const DELETE=1;
const EDIT_BUTTON_UNIT=2;
const RESET_FORM_UNIT=3;
const SET_LOADING=4;
const FETCH_COMPLETE_UNIT=5;
const HANDLE_CHANGES_UNIT=6;
const SUBMIT_COMPLETE_UNIT=7;
const DELETE_DESIGN=8;
const EDIT_DESIGN=9;
const RESET_FORM_DESIGN=10;
const FETCH_DESIGN=11;
const HANDLE_CHANGES_DESIGN=12;
const SUBMIT_COMPLETE_DESIGN=13;
const DELETE_TRANSACTION=14;
const EDIT_TRANSACTION=15;
const RESET_FORM_TRANSACTION=16;
const FETCH_TRANSACTION=17;
const HANDLE_CHANGES_TRANSACTION=18;
const SUBMIT_TRANSACTION=19;
const HANDLE_TRANSACTION_UNIT=20;
const SUBMIT_TRANSACTION_UNIT=21;



export {
    DELETE,EDIT_BUTTON_UNIT,RESET_FORM_UNIT, SET_LOADING, FETCH_COMPLETE_UNIT, HANDLE_CHANGES_UNIT, SUBMIT_COMPLETE_UNIT, DELETE_DESIGN,EDIT_DESIGN,FETCH_DESIGN,HANDLE_CHANGES_DESIGN,RESET_FORM_DESIGN,SUBMIT_COMPLETE_DESIGN, DELETE_TRANSACTION,EDIT_TRANSACTION, RESET_FORM_TRANSACTION, SUBMIT_TRANSACTION, FETCH_TRANSACTION, HANDLE_CHANGES_TRANSACTION, HANDLE_TRANSACTION_UNIT, SUBMIT_TRANSACTION_UNIT
}
